# Generated by Django 5.0 on 2024-06-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w3schools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='w3schools',
            name='ID',
        ),
        migrations.AlterField(
            model_name='w3schools',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
